//姓名：邵新宇 学号：5130379048

//进行宏定义
//定义了元素的长宽，一些限定时间所需的帧数，比如无敌时间2秒，每秒50帧，即为100帧，还定义了系统状态，元素状态，元素类型，射击间隔帧数等
#ifndef PLANEWAR_H
#define PLANEWAR_H

#define PI 3.14159

#define WIN_W 600
#define WIN_H 600
#define PL_W 32
#define PL_H 48
#define WINGMAN_W 24
#define WINGMAN_H 24
#define MIKO_W 32
#define MIKO_H 32
#define SNAIL_W 30
#define SNAIL_H 30
#define BUTTERFLY_W 65
#define BUTTERFLY_H 50
#define SNOWMAN_W 60
#define SNOWMAN_H 50
#define GHOST_W 62
#define GHOST_H 50
#define BOSS_1_W 41
#define BOSS_1_H 62
#define BOSS_2_W 41
#define BOSS_2_H 62
#define BOSS_3_W 60
#define BOSS_3_H 80
#define BOSS_4_W 62
#define BOSS_4_H 62
#define BOSS_5_W 62
#define BOSS_5_H 65
#define BG_W 600
#define BG_H 600
#define SCORE_W 24
#define SCORE_H 24

#define PL_BLOOD 5.0
#define PL_BLOOD_W 120
#define PL_BLOOD_H 10
#define BOSS_BLOOD_W 500
#define BOSS_BLOOD_H 10
#define PL_LIFE_W 15
#define PL_LIFE_H 15
#define AVATAR_W 50
#define AVATAR_H 50

#define PL_BULL_1_W 10
#define PL_BULL_1_H 15
#define SUPER_BULL_W 15
#define SUPER_BULL_H 600
#define POWER_W 32
#define POWER_H 32
#define ENEMY_BULL_W 16
#define ENEMY_BULL_H 16
#define WINGMAN_BULL_W 10
#define WINGMAN_BULL_H 15

#define BLUE_MIKO_SPEED 100
#define RED_MIKO_SPEED 50
#define SNAIL_SPEED 60
#define BUTTERFLY_SPEED 100
#define SNOWMAN_SPEED 80
#define GHOST_SPEED 120
#define PL_SPEED 180
#define POWER_SPEED 20
#define BOSS_1_SPEED 100
#define BOSS_2_SPEED 100
#define BOSS_3_SPEED 100
#define BOSS_4_SPEED 100
#define BOSS_5_SPEED 100


#define PL_BULL_SPEED 240
#define BLUE_MIKO_BULL_SPEED 60
#define RED_MIKO_BULL_SPEED 100
#define SNAIL_BULL_SPEED 130
#define BUTTERFLY_BULL_SPEED 100
#define GHOST_BULL_SPEED 70
#define SNOWMAN_BULL_SPEED 90
#define BOSS_1_BULL_SPEED 100
#define BOSS_2_BULL_SPEED 110
#define BOSS_3_BULL_SPEED 120
#define BOSS_4_BULL_SPEED 150
#define BOSS_5_BULL_SPEED 200
#define RED_WINGMAN_BULL_SPEED  300
#define BLUE_WINGMAN_BULL_SPEED 260

#define BLUE_MIKO_BLOOD 5.0
#define RED_MIKO_BLOOD  3.0
#define SNAIL_BLOOD 25.0
#define BUTTERFLY_BLOOD  12.0
#define SNOWMAN_BLOOD 20.0
#define GHOST_BLOOD  15.0
#define BOSS_1_BLOOD 100.0
#define BOSS_2_BLOOD 150.0
#define BOSS_3_BLOOD 100.0
#define BOSS_4_BLOOD 250.0
#define BOSS_5_BLOOD 120.0

#define BLUE_MIKO_SHOOT_INTERVAL 50
#define RED_MIKO_SHOOT_INTERVAL 200
#define SNAIL_SHOOT_INTERVAL 150
#define SNOWMAN_SHOOT_INTERVAL 50
#define BUTTERFLY_SHOOT_INTERVAL 10
#define GHOST_SHOOT_INTERVAL 30
#define PL_SHOOT_INTERVAL 15
#define BOSS_1_SHOOT_INTERVAL 50
#define BOSS_2_SHOOT_INTERVAL 10
#define BOSS_3_SHOOT_INTERVAL 30
#define BOSS_4_SHOOT_INTERVAL 10
#define BOSS_5_SHOOT_INTERVAL 20
#define RED_WINGMAN_SHOOT_INTERVAL 30
#define BLUE_WINGMAN_SHOOT_INTERVAL 40

#define SUPER_FRAME 120
#define SUPER_BULL_FRAME 300
#define BOSS_SUPER_FRAME 250
#define FROZEN_FRAME 100
#define PASS_FRAME 125
#define BOSS_APPEAR_FRAME 1500
#define BOSS_DEAD_FRAME 300

#define EXPLODE_ENEMY_W 33
#define EXPLODE_ENEMY_H 50

#define EXPLODE_BOSS_W 240
#define EXPLODE_BOSS_H 180

#define PL_BULL_INTERVAL 6


//枚举一些状态
//系统状态，用于改变游戏画面和切换菜单
enum SystemStatus {START,RUNNING,WIN,FAILE,PAUSE,PASS,BOSS_DEAD,BACKGROUND,BGM,OPTION,RANKING,DIFFICULTY};
//游戏关卡
enum GameStage {STAGE_1,STAGE_2,STAGE_3,STAGE_4,STAGE_5};
//移动状态，因为玩家和敌人的元素都是动画，所以用移动状态来选择画不同状态的动画
enum MoveStatus {STAY,LEFT,RIGHT,SHOOT};
//元素状态，其中SUPER是无敌，FROZEN是冰冻，只用于玩家，敌人有专门的布尔值，ADD_BULLET状态是敌人专用，此时敌人加子弹
enum ElementsStatus {SUPER,NORMAL,ADD_BULLET,FROZEN};
//子弹类型
enum BulletType {PLAYER_BULLET_1,SUPER_BULL,BLUE_MIKO_BULLET,RED_MIKO_BULLET,SNAIL_BULLET,SNOWMAN_BULLET,BUTTERFLY_BULLET,GHOST_BULLET,
	             BOSS_1_BULLET,BOSS_2_BULLET,BOSS_3_BULLET,BOSS_4_BULLET,BOSS_5_BULLET,RED_WINGMAN_BULLET,BLUE_WINGMAN_BULLET};
//元素类型，1个玩家，6种敌人，5种boss，2种僚机，8种掉落物品
enum ElementsType {PLAYER_1,BLUE_MIKO,RED_MIKO,SNAIL,BUTTERFLY,SNOWMAN,GHOST,BOSS_1,BOSS_2,BOSS_3,BOSS_4,BOSS_5,
	               POWER_LIFE,POWER_BULL,POWER_BLOOD,RED_WINGMAN,BLUE_WINGMAN,RED_SCORE,BLUE_SCORE,BLACK_SOCRE};

#endif